### ISSUE TITLE
[Enhancement] Open CloudShell terminal faster

### ISSUE THREAD

**Issue by yankay** [cloudtty/cloudtty#165]
In demo dev environment, it needs 5.9s to load the terminal.

Is there any way to make it faster? like 1s.

![企业微信截图_16663510229219](https://user-images.githubusercontent.com/1469319/197183842-732a254e-dd13-4a47-82fc-0971e3a7efb3.png)

**Comment by calvin0327** [comment]
Demo dev env very slow due to spend too mush time to running a cloudtty pod. 
80% of the  time if API is spent running the pod, the alpha env is fast a lot.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/45745657/197666938-9393b0a2-3ee3-4451-9725-f5432256bad5.png">

Can we figure out how to running a cloudtty pod quickly?
1. Can we running a pod in advance?
2. Whether we can reuse one pod ?
