### ISSUE TITLE
Request the token with the window.location.search

### ISSUE THREAD

**Issue by barnettZQG** [cloudtty/cloudtty#178]
https://github.com/cloudtty/cloudtty/blob/40f8e3c357f7321f547ca813454af361c4d07e7a/html/src/components/app.tsx#L14

Issue Reference: https://github.com/kubevela/kubevela/issues/5005

In our use case, the request token of the proxy server is in the `window.location.search`, without it the request is denied.

BTW, The Cloudtty instance works without the token.

**Comment by calvin0327** [comment]
@youhonglian PTAL, thanks

**Comment by panpan0000** [comment]
@youhonglian  and I just dig a bit about the `/token`
By default , the `/token` API will return nothing but no impact the normal behavior.
But when `ttyd` runs with `--credential`(username/password),  the `/token` API will return a "secret"(base64ed user/password) to frontend browser, then frontend will attach the "secret" to  ws(web socket) connection. When the "secret" in the ws is invalid, backend will reject this ws connection request.

That's why @youhonglian  asked whether you have enabled `--credential` for ttyd start parameter.

And moreover, when ttyd runs with `--credential` parameter,  it requires human to type the user/password on the  browser  popup box like below snapshot
![image](https://user-images.githubusercontent.com/14049268/203527534-beefd9eb-e185-4632-a34f-5a10a567ab21.png)

if the user/password is correct, then the `/token` API will return the base64 credit and attach it to ws connection.

We didn't find any way to attach the "user/password" in  location.search in URL . it seems only browser interaction available.


So at the end, when you run ttyd with `--credential`, you can encounter the problem of unauthorized web socket connection.
But if you didn't enable  `--credential`, the issue should not happen.
